# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(help_text='用于代码中引用，只能包含小写字母、数字和下划线', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='供应商ID只能包含小写字母、数字和下划线', regex='^[a-z0-9_]+$')], verbose_name='供应商标识符')),
                ('display_name', models.CharField(help_text='在界面上显示的友好名称', max_length=128, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, help_text='供应商的详细描述信息', null=True, verbose_name='描述')),
                ('website', models.URLField(blank=True, max_length=256, null=True, verbose_name='官方网站')),
                ('supported_services', models.JSONField(default=list, help_text='列表格式，如: ["文本补全", "图像生成", "语音识别"]', verbose_name='支持的服务')),
                ('config_template', models.JSONField(blank=True, default=dict, help_text='供应商特定的配置参数模板', verbose_name='配置模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高', verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-priority', 'display_name'],
                'indexes': [models.Index(fields=['vendor_id'], name='router_vend_vendor__c2c230_idx'), models.Index(fields=['is_active', '-priority'], name='router_vend_is_acti_7eb1bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, choices=[('OpenRouter', 'OpenRouter'), ('frago', 'frago'), ('茶姬', '茶姬'), ('阿里云百炼大模型', '阿里云百炼大模型')], max_length=128, null=True, verbose_name='供应商名称（旧）')),
                ('vendor_id_legacy', models.CharField(blank=True, choices=[('openrouter', 'openrouter'), ('frago', 'frago'), ('chagee', 'chagee'), ('aliyun', 'aliyun')], db_column='vendor_id_old', max_length=64, null=True, verbose_name='供应商标识符（旧）')),
                ('api_key', models.CharField(max_length=256, verbose_name='API密钥')),
                ('description', models.TextField(blank=True, help_text='可用于记录密钥的用途、限制或其他相关信息', null=True, verbose_name='密钥描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='router.vendor', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商API密钥',
                'verbose_name_plural': '供应商API密钥',
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, choices=[('OpenRouter', 'OpenRouter'), ('frago', 'frago'), ('茶姬', '茶姬'), ('阿里云百炼大模型', '阿里云百炼大模型')], max_length=128, null=True, verbose_name='供应商名称（旧）')),
                ('vendor_id_legacy', models.CharField(blank=True, choices=[('openrouter', 'openrouter'), ('frago', 'frago'), ('chagee', 'chagee'), ('aliyun', 'aliyun')], db_column='vendor_id_old', max_length=64, null=True, verbose_name='供应商标识符（旧）')),
                ('endpoint', models.URLField(max_length=256, verbose_name='API端点地址')),
                ('service_type', models.CharField(help_text='如: 文本补全、图像生成、语音识别等', max_length=1000, verbose_name='服务类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='router.vendor', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商端点',
                'verbose_name_plural': '供应商端点',
                'ordering': ['vendor_name', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='模型名称')),
                ('model_id', models.CharField(default='default-model', help_text='调用 API 时使用的模型标识符，如 gpt-3.5-turbo、llama-7b 等', max_length=128, verbose_name='模型标识符')),
                ('model_type', models.CharField(choices=[('text', 'Text'), ('reasoning', 'Reasoning'), ('vision', 'Vision'), ('embedding', 'Embedding'), ('rerank', 'Rerank')], max_length=32, verbose_name='模型类型')),
                ('api_standard', models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'HuggingFace'), ('custom', 'Custom')], max_length=32, verbose_name='模型接口标准')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='用于配置额外的API请求头', null=True, verbose_name='自定义请求头')),
                ('params', models.JSONField(blank=True, default=dict, null=True, verbose_name='模型参数')),
                ('adapter_config', models.JSONField(blank=True, default=dict, help_text='模型特定的适配器配置，如响应解析规则、请求转换规则等', null=True, verbose_name='适配器配置')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('call_count', models.PositiveIntegerField(default=0, verbose_name='调用次数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='调用成功次数')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_models', to='router.vendorendpoint', verbose_name='模型接口')),
            ],
            options={
                'verbose_name': '大语言模型',
                'verbose_name_plural': '大语言模型',
            },
        ),
    ]
