# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('auth_type', models.CharField(choices=[('email', '邮箱注册'), ('feishu', '飞书登录')], default='email', help_text='请使用 UserAccount 管理多种登录方式', max_length=20, verbose_name='认证类型（已废弃）')),
                ('external_id', models.CharField(blank=True, help_text='请使用 UserAccount.provider_account_id', max_length=64, null=True, unique=True, verbose_name='外部平台ID（已废弃）')),
                ('status', models.SmallIntegerField(choices=[(0, '未激活'), (1, '正常'), (2, '封禁')], default=1, verbose_name='用户状态')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('admin', '管理员'), ('super_admin', '超级管理员')], default='user', max_length=20, verbose_name='用户角色')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter链接')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn链接')),
                ('agreed_agreement_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='同意的协议版本')),
                ('agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='同意协议时间')),
                ('reset_token', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='重置令牌')),
                ('reset_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='重置令牌过期时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='待验证邮箱')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='验证令牌')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
            },
        ),
        migrations.CreateModel(
            name='FeishuAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=64, unique=True, verbose_name='飞书OpenID')),
                ('union_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='飞书UnionID')),
                ('access_token', models.CharField(max_length=1512, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(max_length=1512, verbose_name='刷新令牌')),
                ('token_expires_at', models.DateTimeField(verbose_name='令牌过期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_auth', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '飞书认证',
                'verbose_name_plural': '飞书认证',
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True, verbose_name='状态值')),
                ('provider', models.CharField(blank=True, max_length=20, null=True, verbose_name='提供商')),
                ('redirect_url', models.URLField(verbose_name='回调URL')),
                ('code_verifier', models.CharField(blank=True, max_length=128, null=True, verbose_name='PKCE验证码')),
                ('extra_data', models.TextField(blank=True, help_text='存储额外的回调信息', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'OAuth状态',
                'verbose_name_plural': 'OAuth状态',
                'indexes': [models.Index(fields=['-created_at'], name='authenticat_created_8c9e23_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='账号ID')),
                ('type', models.CharField(choices=[('oauth', 'OAuth认证'), ('email', '邮箱密码'), ('credentials', '用户名密码')], max_length=20, verbose_name='账号类型')),
                ('provider', models.CharField(choices=[('email', '邮箱'), ('feishu', '飞书'), ('google', 'Google'), ('github', 'GitHub'), ('wechat', '微信')], max_length=20, verbose_name='提供商')),
                ('provider_account_id', models.CharField(help_text='如飞书的open_id、Google的sub等', max_length=128, verbose_name='提供商账号ID')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='访问令牌')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='刷新令牌')),
                ('token_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='令牌类型')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('scope', models.TextField(blank=True, null=True, verbose_name='授权范围')),
                ('id_token', models.TextField(blank=True, null=True, verbose_name='ID令牌')),
                ('is_primary', models.BooleanField(default=False, help_text='用户的主要登录方式', verbose_name='是否主账号')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('provider_profile', models.JSONField(blank=True, help_text='存储提供商返回的完整用户信息', null=True, verbose_name='提供商用户信息')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户账号',
                'verbose_name_plural': '用户账号',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='配置文件ID')),
                ('subscription_type', models.CharField(choices=[('free_user', '免费用户'), ('vip_user', 'VIP用户'), ('enterprise_user', '企业用户'), ('max_user', 'Max用户')], default='free_user', help_text='用户的订阅等级，决定配额和功能权限', max_length=20, verbose_name='订阅类型')),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('energy', 'Energy'), ('media', 'Media & Entertainment'), ('telecommunications', 'Telecommunications'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('government', 'Government'), ('non_profit', 'Non-Profit'), ('consulting', 'Consulting'), ('legal', 'Legal'), ('insurance', 'Insurance'), ('pharmaceutical', 'Pharmaceutical'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('logistics', 'Logistics & Supply Chain'), ('e_commerce', 'E-Commerce'), ('other', 'Other')], help_text='用户或组织所在的行业领域', max_length=30, null=True, verbose_name='所属行业')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='存储用户的背景信息、专业领域等', null=True, verbose_name='上下文数据')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='用于分类和个性化的标签列表', size=None, verbose_name='用户标签')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='存储用户的各种偏好设置', null=True, verbose_name='用户偏好')),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='定义用户可以访问的工具、模型等资源', null=True, verbose_name='能力配置')),
                ('quotas', models.JSONField(blank=True, default=dict, help_text='各种资源的使用配额限制', null=True, verbose_name='使用配额')),
                ('usage_stats', models.JSONField(blank=True, default=dict, help_text='累计的使用统计数据', null=True, verbose_name='使用统计')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户配置文件',
                'verbose_name_plural': '用户配置文件',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_d74434_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='authenticat_status_35d44c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='authenticat_role_7fb088_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['token'], name='authenticat_token_368f59_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', '-created_at'], name='authenticat_user_id_d8a553_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user', 'is_primary'], name='authenticat_user_id_cb5d80_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['provider', 'provider_account_id'], name='authenticat_provide_8be940_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together={('provider', 'provider_account_id'), ('user', 'provider')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='authenticat_user_id_35f8a3_idx'),
        ),
    ]
