# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('hupijiao', '虎皮椒支付'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50, unique=True, verbose_name='支付服务商')),
                ('app_id', models.CharField(max_length=200, verbose_name='应用ID')),
                ('app_secret', models.CharField(max_length=500, verbose_name='应用密钥')),
                ('api_url', models.URLField(blank=True, max_length=500, verbose_name='API地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_test_mode', models.BooleanField(default=False, verbose_name='测试模式')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='其他配置参数', verbose_name='额外配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付配置',
                'verbose_name_plural': '支付配置',
                'db_table': 'payment_configs',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='商户系统内部订单号', max_length=64, unique=True, verbose_name='订单号')),
                ('trade_order_id', models.CharField(blank=True, help_text='支付平台返回的交易号', max_length=128, null=True, verbose_name='第三方交易号')),
                ('payment_method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝')], max_length=20, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='货币类型')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('product_id', models.CharField(blank=True, help_text='关联的商品或服务ID', max_length=100, null=True, verbose_name='商品ID')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='支付页面URL')),
                ('qrcode_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='支付二维码URL')),
                ('notify_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='异步通知URL')),
                ('return_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='同步返回URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='存储额外的支付相关信息', verbose_name='扩展数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('request', '请求'), ('response', '响应'), ('callback', '回调'), ('error', '错误')], max_length=20, verbose_name='日志类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='日志数据')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='错误代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.paymentorder', verbose_name='支付订单')),
            ],
            options={
                'verbose_name': '支付日志',
                'verbose_name_plural': '支付日志',
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_type', models.CharField(choices=[('notify', '异步通知'), ('return', '同步返回')], max_length=20, verbose_name='回调类型')),
                ('raw_data', models.JSONField(help_text='支付平台返回的原始数据', verbose_name='原始数据')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='签名')),
                ('is_verified', models.BooleanField(default=False, verbose_name='签名验证通过')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='payment.paymentorder', verbose_name='支付订单')),
            ],
            options={
                'verbose_name': '支付回调记录',
                'verbose_name_plural': '支付回调记录',
                'db_table': 'payment_callbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['order_id'], name='payment_ord_order_i_d7c1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='payment_ord_user_id_5f4b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['created_at'], name='payment_ord_created_57a748_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['order', 'created_at'], name='payment_log_order_i_23d6ef_idx'),
        ),
    ]
