# Generated by Django 5.1.5 on 2025-10-09 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFExtractorTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件存储路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('error', '错误')], default='pending', max_length=20, verbose_name='任务状态')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('processed_pages', models.IntegerField(default=0, verbose_name='已处理页数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'PDF提取任务',
                'verbose_name_plural': 'PDF提取任务',
                'db_table': 'toolkit_pdf_extractor_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
