# Generated by Django 5.1.5 on 2025-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0002_pdfextractortask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfextractortask',
            name='feishu_doc_url',
            field=models.TextField(blank=True, help_text='格式: https://feishu.cn/docx/{document_id}', null=True, verbose_name='飞书文档链接'),
        ),
    ]
