# Generated by Django 5.2.8 on 2025-11-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_pdfextractortask_feishu_doc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfextractortask',
            name='page_range_end',
            field=models.IntegerField(blank=True, help_text='结束页码（包含），为空表示到最后一页', null=True, verbose_name='结束页码'),
        ),
        migrations.AddField(
            model_name='pdfextractortask',
            name='page_range_start',
            field=models.IntegerField(blank=True, help_text='起始页码（包含），为空表示从第一页开始', null=True, verbose_name='起始页码'),
        ),
        migrations.AddField(
            model_name='pdfextractortask',
            name='target_language',
            field=models.CharField(choices=[('zh', '中文'), ('en', '英文')], default='zh', max_length=10, verbose_name='目标语言'),
        ),
        migrations.AddField(
            model_name='pdfextractortask',
            name='translate',
            field=models.BooleanField(default=False, verbose_name='是否翻译'),
        ),
    ]
