# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session_id', models.CharField(max_length=64, unique=True, verbose_name='会话ID')),
                ('state', models.BooleanField(default=True, verbose_name='状态')),
                ('session_length', models.PositiveIntegerField(default=0, verbose_name='会话长度 (Token 总量)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
            },
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_app', models.CharField(max_length=64, verbose_name='来源应用')),
                ('source_type', models.CharField(max_length=16, verbose_name='来源类型')),
                ('prompt_text', models.TextField(blank=True, null=True, verbose_name='提示文本')),
                ('prompt_images', models.JSONField(blank=True, default=list, null=True, verbose_name='提示图片')),
                ('prompt_files', models.JSONField(blank=True, default=list, null=True, verbose_name='提示文件')),
                ('model', models.CharField(max_length=64, verbose_name='模型名称')),
                ('prompt_params', models.JSONField(blank=True, default=dict, null=True, verbose_name='提示参数')),
                ('origin_response', models.JSONField(default=dict, verbose_name='原始响应')),
                ('response', models.JSONField(default=dict, verbose_name='拼装后响应')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qas', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='chat_sessions.session', verbose_name='会话')),
            ],
            options={
                'verbose_name': '问答记录',
                'verbose_name_plural': '问答记录',
            },
        ),
        migrations.CreateModel(
            name='AgenticLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField(help_text='步骤顺序')),
                ('log_type', models.CharField(choices=[('PLANNER', '规划器'), ('TOOL_CALL', '工具调用'), ('TOOL_RESULT', '工具结果'), ('REFLECTION', '反思'), ('FINAL_ANSWER', '最终答案')], help_text='日志类型', max_length=50)),
                ('details', models.JSONField(help_text='每一步的详细数据（如 planner 的思考、工具的输入输出等）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('task', models.ForeignKey(help_text='关联的 Agent 任务', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agentic.agenttask')),
                ('qa_record', models.ForeignKey(blank=True, help_text='关联的 QA 记录，允许在 QA 记录最终生成前就创建日志', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_logs', to='chat_sessions.qa')),
            ],
            options={
                'verbose_name': 'Agent 运行日志',
                'verbose_name_plural': 'Agent 运行日志',
                'ordering': ['task', 'step_order'],
                'unique_together': {('task', 'step_order')},
            },
        ),
    ]
