# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="此配置集的唯一名称，例如 '默认 Groq Llama4 Aliyun V3'", max_length=255, unique=True, verbose_name='配置名称')),
                ('is_active', models.BooleanField(default=False, help_text='一次只能激活一个配置。系统将使用激活的配置。', verbose_name='是否激活')),
                ('llm_model_name', models.CharField(default='meta-llama/llama-4-maverick-17b-128e-instruct', help_text="具体的模型名称，例如 'gpt-3.5-turbo', 'meta-llama/llama-4-maverick-17b-128e-instruct'。", max_length=255, verbose_name='LLM 模型名称')),
                ('llm_temperature', models.FloatField(default=0.35, help_text='LLM 的采样温度，例如 0.7。', verbose_name='LLM 温度参数')),
                ('embedder_model_name', models.CharField(default='text-embedding-v3', help_text="Embeddings 的具体模型名称，例如 'text-embedding-ada-002', 'text-embedding-v3'。", max_length=255, verbose_name='Embedder 模型名称')),
                ('embedder_dimensions', models.PositiveIntegerField(default=1024, help_text='Embeddings 的维度，例如 1024。', verbose_name='Embedder 维度')),
                ('vector_store_provider', models.CharField(choices=[('qdrant', 'Qdrant')], default='qdrant', help_text='向量存储的提供商。', max_length=50, verbose_name='向量存储提供商')),
                ('qdrant_host', models.CharField(default='localhost', help_text='Qdrant 服务的主机名或 IP 地址。', max_length=255, verbose_name='Qdrant 主机')),
                ('qdrant_port', models.PositiveIntegerField(default=6333, help_text='Qdrant 服务的端口号。', verbose_name='Qdrant 端口')),
                ('qdrant_api_key', models.CharField(blank=True, help_text='Qdrant 服务的 API 密钥（如果已配置）。', max_length=512, null=True, verbose_name='Qdrant API 密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '知识库配置',
                'verbose_name_plural': '知识库配置',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for the knowledge collection, e.g., 'product_manuals', 'faq_data'.", max_length=255, unique=True, verbose_name='Collection Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of this knowledge collection.', null=True, verbose_name='Description')),
                ('qdrant_collection_name', models.CharField(blank=True, help_text='Specific Qdrant collection name, if explicitly managed.', max_length=255, null=True, verbose_name='Qdrant Collection Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_collections_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Knowledge Collection',
                'verbose_name_plural': 'Knowledge Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('add_data', 'Add Data'), ('search_query', 'Search Query'), ('search_data', 'Search Data'), ('get_data', 'Get Data'), ('delete_data', 'Delete Data')], db_index=True, help_text="Type of interaction, e.g., 'add_data', 'search_query'.", max_length=50, verbose_name='Interaction Type')),
                ('request_payload', models.JSONField(blank=True, help_text='Sanitized main content of the API request.', null=True, verbose_name='Request Payload')),
                ('response_payload', models.JSONField(blank=True, help_text='Sanitized main content of the API response.', null=True, verbose_name='Response Payload')),
                ('llm_prompt_data', models.JSONField(blank=True, help_text='Prompt and context sent to LLM, if applicable.', null=True, verbose_name='LLM Prompt Data')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Processing time for the interaction in milliseconds.', null=True, verbose_name='Duration (ms)')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP response status code.', null=True, verbose_name='Status Code')),
                ('error_message', models.TextField(blank=True, help_text='Error message if an error occurred.', null=True, verbose_name='Error Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='knowledge.knowledgecollection', verbose_name='Collection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_interactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Knowledge Interaction',
                'verbose_name_plural': 'Knowledge Interactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', help_text='The actual content of the knowledge item.', verbose_name='Content')),
                ('item_type', models.CharField(choices=[('text', 'Text'), ('document', 'Document'), ('faq', 'FAQ'), ('memory', 'Memory'), ('reference', 'Reference')], db_index=True, default='text', help_text='Type of the knowledge item.', max_length=50, verbose_name='Item Type')),
                ('source_identifier', models.CharField(blank=True, db_index=True, help_text='Unique identifier for the original data source, e.g., filename, URL, DB record ID.', max_length=512, null=True, verbose_name='Source Identifier')),
                ('data_hash', models.CharField(blank=True, db_index=True, help_text='Hash of the original data content to detect changes.', max_length=128, null=True, verbose_name='Data Hash')),
                ('metadata', models.JSONField(blank=True, help_text='Arbitrary metadata related to this item, e.g., creation date, author, tags.', null=True, verbose_name='Metadata')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('active', 'Active'), ('archived', 'Archived'), ('error', 'Error')], db_index=True, default='active', help_text='Status of this knowledge item.', max_length=50, verbose_name='Status')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp of the last access or retrieval.', null=True, verbose_name='Last Accessed At')),
                ('collection', models.ForeignKey(help_text='The collection this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knowledge.knowledgecollection', verbose_name='Collection')),
            ],
            options={
                'verbose_name': 'Knowledge Item',
                'verbose_name_plural': 'Knowledge Items',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['collection', 'status'], name='knowledge_k_collect_d60cbb_idx')],
            },
        ),
    ]
