# Generated by Django 5.1.5 on 2025-09-17 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='图ID')),
                ('name', models.CharField(max_length=200, verbose_name='图名称')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认图')),
                ('config', models.JSONField(blank=True, default=dict, help_text='存储图的全局配置信息', verbose_name='图配置')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graphs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '图定义',
                'verbose_name_plural': '图定义',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EdgeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.CharField(help_text='图内唯一的边标识', max_length=100, verbose_name='边ID')),
                ('source_node_id', models.CharField(max_length=100, verbose_name='源节点ID')),
                ('target_node_id', models.CharField(max_length=100, verbose_name='目标节点ID')),
                ('condition', models.TextField(blank=True, help_text='用于条件路由的表达式，为空表示无条件', verbose_name='条件表达式')),
                ('priority', models.IntegerField(default=0, help_text='多条边时的执行优先级，数字越小优先级越高', verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='agentic_graph.graphdefinition', verbose_name='所属图')),
            ],
            options={
                'verbose_name': '边定义',
                'verbose_name_plural': '边定义',
                'ordering': ['graph', 'priority', 'edge_id'],
            },
        ),
        migrations.CreateModel(
            name='NodeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(help_text='图内唯一的节点标识', max_length=100, verbose_name='节点ID')),
                ('node_type', models.CharField(choices=[('planner', 'Planner - 规划节点'), ('tool_call', 'Tool Call - 工具调用节点'), ('reflection', 'Reflection - 反思节点'), ('output_selector', 'Output Selector - 输出选择节点'), ('output', 'Output - 输出节点'), ('end', 'End - 结束节点'), ('start', 'Start - 开始节点')], max_length=20, verbose_name='节点类型')),
                ('node_name', models.CharField(help_text='节点的显示名称', max_length=200, verbose_name='节点名称')),
                ('tool_name', models.CharField(blank=True, help_text='关联的工具名称', max_length=100, verbose_name='工具名称')),
                ('config', models.JSONField(blank=True, default=dict, help_text='节点的具体配置参数', verbose_name='节点配置')),
                ('position', models.JSONField(blank=True, default=dict, help_text='节点在图中的位置坐标', verbose_name='位置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agentic_graph.graphdefinition', verbose_name='所属图')),
            ],
            options={
                'verbose_name': '节点定义',
                'verbose_name_plural': '节点定义',
                'ordering': ['graph', 'node_id'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='执行ID')),
                ('session_id', models.CharField(db_index=True, help_text='关联的会话标识', max_length=100, verbose_name='会话ID')),
                ('turn_id', models.CharField(blank=True, help_text='多轮对话中的轮次标识', max_length=100, verbose_name='轮次ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='执行状态')),
                ('current_node', models.CharField(blank=True, help_text='当前执行到的节点ID，为空表示已完成', max_length=100, verbose_name='当前节点')),
                ('runtime_state', models.JSONField(default=dict, help_text='完整的 RuntimeState 数据，覆盖更新', verbose_name='运行时状态')),
                ('result', models.JSONField(blank=True, help_text='最终的执行结果', null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, help_text='执行失败时的错误信息', verbose_name='错误信息')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='总成本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外的元数据信息', verbose_name='元数据')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='agentic_graph.graphdefinition', verbose_name='使用的图定义')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行用户')),
            ],
            options={
                'verbose_name': '任务执行',
                'verbose_name_plural': '任务执行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('node_id', models.CharField(max_length=100, verbose_name='节点ID')),
                ('node_type', models.CharField(max_length=20, verbose_name='节点类型')),
                ('node_name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('step_number', models.IntegerField(help_text='执行的顺序编号', verbose_name='步骤序号')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='节点接收的输入数据快照', verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='节点产生的输出数据', verbose_name='输出数据')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], default='success', max_length=20, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, help_text='执行失败时的错误信息', verbose_name='错误信息')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示Token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='完成Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='执行耗时(ms)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='节点特定的额外信息', verbose_name='元数据')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agentic_graph.taskexecution', verbose_name='所属任务执行')),
            ],
            options={
                'verbose_name': '步骤记录',
                'verbose_name_plural': '步骤记录',
                'ordering': ['task_execution', 'step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='graphdefinition',
            index=models.Index(fields=['is_active', '-created_at'], name='agentic_gra_is_acti_1694ee_idx'),
        ),
        migrations.AddIndex(
            model_name='graphdefinition',
            index=models.Index(fields=['name', 'version'], name='agentic_gra_name_192102_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='graphdefinition',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='edgedefinition',
            index=models.Index(fields=['graph', 'source_node_id'], name='agentic_gra_graph_i_dd8516_idx'),
        ),
        migrations.AddIndex(
            model_name='edgedefinition',
            index=models.Index(fields=['graph', 'target_node_id'], name='agentic_gra_graph_i_c6f6bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='edgedefinition',
            unique_together={('graph', 'edge_id')},
        ),
        migrations.AddIndex(
            model_name='nodedefinition',
            index=models.Index(fields=['graph', 'node_type'], name='agentic_gra_graph_i_7ddc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedefinition',
            index=models.Index(fields=['tool_name'], name='agentic_gra_tool_na_0cb01d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodedefinition',
            unique_together={('graph', 'node_id')},
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['session_id', '-created_at'], name='agentic_gra_session_e64b48_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['user', 'status', '-created_at'], name='agentic_gra_user_id_17e975_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['graph', 'status'], name='agentic_gra_graph_i_3d9bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status', '-updated_at'], name='agentic_gra_status_452314_idx'),
        ),
        migrations.AddIndex(
            model_name='steprecord',
            index=models.Index(fields=['task_execution', 'step_number'], name='agentic_gra_task_ex_39f842_idx'),
        ),
        migrations.AddIndex(
            model_name='steprecord',
            index=models.Index(fields=['task_execution', 'node_type'], name='agentic_gra_task_ex_653379_idx'),
        ),
        migrations.AddIndex(
            model_name='steprecord',
            index=models.Index(fields=['result', '-started_at'], name='agentic_gra_result_a24ff1_idx'),
        ),
    ]
