# Generated by Django 5.1.5 on 2025-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdefinition',
            name='entry_point',
            field=models.CharField(default='START', help_text='图的起始节点ID', max_length=100, verbose_name='入口节点'),
        ),
    ]
