"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, quote

# 检查 torch 是否可用
try:
    import torch
    GPU_AVAILABLE = torch.cuda.is_available()
except ImportError:
    GPU_AVAILABLE = False

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv()

# 测试环境控制
IS_TEST_ENV = os.getenv('IS_TEST_ENV', 'False').lower() == 'true'

# 安全配置 (从.env加载)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-default-key")
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

# 生产环境域名配置 (从.env加载)
# 格式说明:
# ALLOWED_HOSTS - 允许访问的域名/IP列表(逗号分隔)，用于防止HTTP Host头攻击
# CSRF_TRUSTED_ORIGINS - 信任的源站URL列表(包含协议)，用于CSRF保护
# CORS_ALLOWED_ORIGINS - 允许跨域访问的前端URL列表，用于CORS控制
#
# 三者区别:
# 1. ALLOWED_HOSTS: 服务端安全验证
# 2. CSRF_TRUSTED_ORIGINS: 表单提交安全验证
# 3. CORS_ALLOWED_ORIGINS: 前端API调用权限控制
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = (
    os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS")
    else []
)

# Web API 回调配置
WEB_API_BASE_URL = os.environ.get('WEB_API_BASE_URL', 'http://localhost:3000/_studio/api')
INTERNAL_API_TOKEN = os.environ.get('INTERNAL_API_TOKEN', 'default-internal-token-change-in-production')

CORS_ALLOWED_ORIGINS = (
    os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if os.getenv("CORS_ALLOWED_ORIGINS")
    else []
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

parsed_server_host = urlparse(os.getenv("SERVER_HOST", "http://localhost:8000"))

# 优先使用环境变量中的FORCE_SCRIPT_NAME，如果没有则从SERVER_HOST解析
if os.getenv("FORCE_SCRIPT_NAME"):
    FORCE_SCRIPT_NAME = os.getenv("FORCE_SCRIPT_NAME")
else:
    FORCE_SCRIPT_NAME = parsed_server_host.path if parsed_server_host.path else None

# 生产环境默认配置
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 关闭SECURE_SSL_REDIRECT，因为我们通过nginx反向代理处理SSL
    # 这样可以避免循环重定向问题
    SECURE_SSL_REDIRECT = False

# Jazzmin 配置 - 美化 Django Admin 界面
JAZZMIN_SETTINGS = {
    # 标题和品牌
    "site_title": "AI中台管理系统",
    "site_header": "AI中台",
    "site_brand": "AI Platform",
    "site_logo": None,  # 可以设置为 "images/logo.png"
    "site_logo_classes": "img-circle",
    "site_icon": None,  # 可以设置为 "fas fa-brain"
    
    # 欢迎信息
    "welcome_sign": "欢迎访问 AI 中台管理系统",
    "copyright": "AI Platform © 2025",
    
    # 搜索模型
    "search_model": ["authentication.User", "llm.LLMCallLog"],
    
    # 字段图标
    "icons": {
        "auth": "fas fa-users-cog",
        "authentication.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # LLM 应用
        "llm.LLMCallLog": "fas fa-history",
        "llm.LLMTokenUsage": "fas fa-chart-line",
        "llm.LLMModelPrice": "fas fa-dollar-sign",
        "llm.LLMRequestCache": "fas fa-database",
        
        # Router 应用
        "router.LLMModel": "fas fa-robot",
        "router.VendorEndpoint": "fas fa-server",
        "router.VendorAPIKey": "fas fa-key",
        
        # Chat 应用
        
        # Knowledge 应用
        "knowledge.KnowledgeCollection": "fas fa-book",
        "knowledge.Document": "fas fa-file-alt",
        
        # Agentic 应用
        "agentic.Graph": "fas fa-project-diagram",
        "agentic.Node": "fas fa-circle-nodes",
        "agentic.Task": "fas fa-tasks",
        
        # Webapps
        "webapps.pagtive.Project": "fas fa-folder-open",
        "webapps.payment.Order": "fas fa-shopping-cart",
        "webapps.chat.ChatMessage": "fas fa-message",
        
        # Customized
        "customized.customization.CustomizationTask": "fas fa-cog",
        "customized.pdf_converter.PDFConversionTask": "fas fa-file-pdf",
    },
    
    # 默认图标
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # 自定义 CSS/JS
    "custom_css": "admin/css/nextjs-theme.css",
    "custom_js": None,
    "use_google_fonts_cdn": False,  # 使用本地字体，避免访问 Google
    "show_ui_builder": False,
    
    # 用户菜单项
    "usermenu_links": [
        {"name": "文档", "url": "/api/docs/", "new_window": True},
        {"model": "authentication.user"},
        {"name": "支持", "url": "https://github.com/your-org/your-repo/issues", "new_window": True},
    ],
    
    # 顶部菜单
    "topmenu_links": [
        {"name": "首页", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API 文档", "url": "/api/docs/", "new_window": True},
        {"model": "authentication.User"},
        {"app": "llm"},
    ],
    
    # 侧边栏
    "show_sidebar": True,
    "navigation_expanded": False,  # 默认折叠左侧菜单
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        # 业务核心模块 - 最高优先级
        "agentic",              # Agentic工作流
        "agentic_graph",        # Agentic Graph引擎
        "knowledge",            # 知识库

        # 业务功能模块
        "webapps.chat",         # Chat应用
        "webapps.payment",      # 支付管理
        "webapps.pagtive",      # Pagtive应用
        "customized.customization",  # 定制功能
        "customized.image_editor",   # 图片编辑器

        # 基础服务模块
        "llm",                  # LLM配置
        "router",               # 路由配置
        "tools",                # 工具管理
        "mineru",              # PDF处理

        # 系统管理模块
        "authentication",       # 用户认证
        "access_control",      # 访问控制
        "service_api",         # 服务API

        # Django默认模块
        "auth",                # Django认证
    ],
    
    # 自定义应用排序和快速链接
    "custom_links": {
        "agentic": [{
            "name": "🚀 创建新工作流",
            "url": "admin:agentic_graph_add",
            "icon": "fas fa-plus-circle",
            "permissions": ["agentic.add_graph"]
        }],
        "agentic_graph": [{
            "name": "📊 任务执行监控",
            "url": "admin:agentic_graph_taskexecution_changelist",
            "icon": "fas fa-tasks",
            "permissions": ["agentic_graph.view_taskexecution"]
        }],
        "llm": [{
            "name": "📈 LLM使用统计",
            "url": "admin:llm_llmtokenusage_changelist",
            "icon": "fas fa-chart-bar",
            "permissions": ["llm.view_llmtokenusage"]
        }],
        "knowledge": [{
            "name": "📚 知识库总览",
            "url": "admin:knowledge_knowledgecollection_changelist",
            "icon": "fas fa-database",
            "permissions": ["knowledge.view_knowledgecollection"]
        }],
    },
    
    # UI 调整
    "changeform_format": "horizontal_tabs",  # 表单布局: horizontal_tabs, vertical_tabs, carousel, single
    "changeform_format_overrides": {
        "auth.user": "carousel",
        "auth.group": "vertical_tabs",
    },
    
    # 主题设置
    "theme": "default",  # 使用默认主题作为基础，通过自定义CSS覆盖
    "dark_mode_theme": None,  # 不需要单独的暗色模式
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
    # 相关模型展示
    "related_modal_active": True,
    "show_changeform_submit": True,
    
    # 语言代码
    "language_chooser": False,
}

# UI 主题配置 - Next.js风格纯黑银白配色
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,  # 启用更小的正文字体
    "brand_small_text": False,
    "brand_colour": None,  # 不使用预设颜色，由自定义CSS控制
    "accent": None,  # 不使用预设强调色
    "navbar": "navbar-dark",  # 基础深色导航栏
    "no_navbar_border": True,  # 去掉边框让界面更简洁
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",  # 深色侧边栏
    "sidebar_nav_small_text": True,  # 侧边栏使用小字体
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,  # 子菜单缩进
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "default",  # 使用默认主题作为基础
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True,
}

# Application definition
INSTALLED_APPS = [
    "corsheaders",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_redis",  # Redis 缓存后端
    "django_rename_app",
    "authentication",
    "service_api",
    "router",
    "llm",  # llm 调用方法
    "access_control",
    "customized.customization",
    # "customized.delivery_performance",  # 应用已移除
    # "customized.pdf_converter",  # 应用已移除
    "customized.image_editor",
    "knowledge",
    "webapps",  # Web应用集合
    "webapps.chat",  # Chat子应用
    "webapps.pagtive",  # Pagtive子应用
    "webapps.payment",  # Payment支付子应用
    "webapps.toolkit",  # 工具集应用
    "webapps.moments",  # 公司圈事件处理
    "webapps.xiaohongshu",  # 小红书舆情监控
    "webapps.market",  # frago Cloud 市场 - Recipe 市场与会话同步
    "agentic",  # 用于构建和管理有状态、多角色的代理（Agent）应用
    "agentic_graph",  # 新的 Graph 处理引擎，与原 agentic 应用隔离
    "tools",  # 用于统一管理和承载 Agent 工具集
    # "django_celery_results", # Celery 结果后端，不再使用，改用Redis DB 2了
    "mineru",  # MinerU PDF 解析服务
    "dataset_downloader",  # 数据集下载任务管理
    "test_app",  # 测试应用
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # 添加 WhiteNoise 中间件
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "authentication.middleware.EnsureUserProfileMiddleware",  # 确保用户有UserProfile
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 允许同源 iframe（Django Admin popup 窗口需要）
X_FRAME_OPTIONS = "SAMEORIGIN"

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),  # 添加全局templates目录
            os.path.join(BASE_DIR, "login/templates")
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database

# 数据库配置
# 根据端口判断是否使用 PgBouncer
DB_PORT = os.getenv("DB_PORT", "6432")
IS_PGBOUNCER = DB_PORT == "6432"  # 6432 是 PgBouncer 默认端口

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # 使用原生后端
        "NAME": os.getenv("DB_DATABASE", "X"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": DB_PORT,
        # PgBouncer 环境必须为 0，直连环境可以使用连接池
        "CONN_MAX_AGE": 0 if IS_PGBOUNCER else 600,  # 直连时使用 10 分钟连接池
        "CONN_HEALTH_CHECKS": not IS_PGBOUNCER,  # 直连时启用健康检查
        "OPTIONS": {
            "connect_timeout": 5,
        }
    }
}

# 直连 PostgreSQL 时添加 keepalive 参数
if not IS_PGBOUNCER:
    DATABASES["default"]["OPTIONS"].update({
        "keepalives": 1,
        "keepalives_idle": 30,
        "keepalives_interval": 10,
        "keepalives_count": 5,
    })

# 不再需要条件判断和配置覆盖
# 不要调用 get_database_config，它会添加不兼容的参数
# DATABASES['default'] = get_database_config(DATABASES['default'])  # 禁用

# Redis Configuration
# ------------------------------------------------------------------------------
# 统一配置 Redis 连接信息，供 Django Cache 和 Celery 使用
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", None)
REDIS_PASSWORD_QUOTED = quote(REDIS_PASSWORD) if REDIS_PASSWORD else None

# Cache Configuration
# ------------------------------------------------------------------------------
CACHE_DB = os.getenv("CACHE_DB", "1")
CACHE_LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}/{CACHE_DB}"
if REDIS_PASSWORD:
    # 使用 URL 编码后的密码构建连接字符串，以处理特殊字符
    CACHE_LOCATION = f"redis://:{REDIS_PASSWORD_QUOTED}@{REDIS_HOST}:{REDIS_PORT}/{CACHE_DB}"

CACHE_MIDDLEWARE_SECONDS = int(
    os.getenv("CACHE_MIDDLEWARE_SECONDS", "900")
)  # 默认15分钟
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_LOCATION", CACHE_LOCATION),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 500},  # 增加连接池以支持高并发
            # 密码已在 LOCATION URL 中提供，此处无需重复设置
            # "PASSWORD": REDIS_PASSWORD if REDIS_PASSWORD else "",
        },
        "KEY_PREFIX": "X",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "access_control/static"),
]

# Media files (for user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# OSS 配置 - 用于生产环境直链访问
# 开发环境：使用本地 /media/ 路径
# 生产环境：使用 OSS 公开域名直链（避免流量经过服务器）
OSS_PUBLIC_DOMAIN = os.getenv('OSS_PUBLIC_DOMAIN', '')

# 开发环境后端 URL（用于前端跨域访问图片）
# 开发环境：前端在 3000 端口，后端在 6066 端口，需要完整URL才能访问图片
# 生产环境：使用 OSS 直链，不需要此配置
DEV_BACKEND_URL = 'http://127.0.0.1:6066'

# Media URL 前缀（根据环境自动选择）
# DEBUG=True: 开发环境后端完整 URL http://127.0.0.1:6066/media/
# DEBUG=False 且配置了 OSS: OSS 直链
MEDIA_URL_PREFIX = f'{DEV_BACKEND_URL}/media/' if DEBUG else (OSS_PUBLIC_DOMAIN + '/' if OSS_PUBLIC_DOMAIN else '/media/')

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
AUTH_USER_MODEL = "authentication.User"

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated"
    ]
}

# JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),  # 访问令牌有效期
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),   # 刷新令牌有效期
    "ROTATE_REFRESH_TOKENS": True,                 # 刷新时轮换刷新令牌
    "BLACKLIST_AFTER_ROTATION": True,              # 轮换后将旧刷新令牌拉黑
    "ALGORITHM": "HS256",                          # 加密算法
    "AUTH_TOKEN_CLASSES": (
        "rest_framework_simplejwt.tokens.AccessToken",
    ),  # 明确指定token类型
    # --- 用户ID相关配置 ---
    # 修复 token_not_valid 问题：确保 JWT 能正确识别用户模型的主键字段
    "USER_ID_FIELD": "id",       # 用户模型的主键字段名（AbstractUser 默认使用 'id'）
    "USER_ID_CLAIM": "user_id",  # JWT payload 中存储用户ID的字段名
    # --- End 用户ID相关配置 ---
    # --- Cookie相关配置 ---
    # 'AUTH_HEADER_TYPES': ('Bearer',), # 默认值，如只用Cookie可保留或移除
    "AUTH_COOKIE": "access_token",           # JWT访问令牌的Cookie名称
    "AUTH_COOKIE_REFRESH": "refresh_token",  # 刷新令牌的Cookie名称（可选，若通过Cookie处理刷新）
    "AUTH_COOKIE_HTTP_ONLY": True,           # 仅HTTP可访问
    "AUTH_COOKIE_SECURE": not DEBUG,         # 生产环境需为True（需HTTPS）
    "AUTH_COOKIE_SAMESITE": "Lax",           # Cookie SameSite属性，可选'Strict'或'None'
    "AUTH_COOKIE_PATH": "/",                 # Cookie路径
    "AUTH_COOKIE_DOMAIN": None,              # 生产环境可设置为你的域名，如".example.com"
    # --- End Cookie相关配置 ---
}

# Feishu
FEISHU = {
    "APP_ID": os.getenv("FEISHU_APP_ID", ""),
    "APP_SECRET": os.getenv("FEISHU_APP_SECRET", ""),
    "OAUTH": {
        "REDIRECT_URI": f"{os.getenv('SERVER_HOST', 'http://localhost:8000')}/api/access/callback/",  # 指向 access_control 应用的处理回调的视图
        "AUTHORIZATION_URL": "https://accounts.feishu.cn/open-apis/authen/v1/authorize",
        "ACCESS_TOKEN_URL": "https://open.feishu.cn/open-apis/authen/v2/oauth/token",
        "REFRESH_TOKEN_URL": "https://open.feishu.cn/open-apis/authen/v1/refresh_access_token",
        "USER_INFO_URL": "https://open.feishu.cn/open-apis/authen/v1/user_info",
        "SCOPES": [
            "component:user_profile",  # 获取用户基本信息
            "contact:contact.base:readonly",  # 查看通讯录联系人信息
            "contact:department.base:readonly",  # 查看通讯录部门信息
            "offline_access",  # 允许刷新 user_access_token，在用户离线时访问已授权数据
            # 云文档读写权限
            "docs:doc",  # 旧版文档：增删改文档及内容
            "docx:document",  # 新版文档：创建及编辑文档
            "sheets:spreadsheet",  # 电子表格：增删改表格、行列数据、视图等
            "drive:drive",  # 云空间：查看、编辑和管理所有文件
            "wiki:wiki",  # 知识库：查看、编辑和管理知识库
            # 多维表格权限（飞书不支持通配符，需逐个声明）
            # 应用级别
            "base:app:copy",  # 复制多维表格
            "base:app:create",  # 创建多维表格
            "base:app:read",  # 获取多维表格元数据
            "base:app:update",  # 更新多维表格元数据
            # 协作者管理
            "base:collaborator:create",  # 新增协作者
            "base:collaborator:delete",  # 删除协作者
            "base:collaborator:read",  # 列出协作者
            # 仪表盘
            "base:dashboard:copy",  # 复制仪表盘
            "base:dashboard:read",  # 获取仪表盘信息
            # 字段管理
            "base:field:create",  # 新增字段
            "base:field:delete",  # 删除字段
            "base:field:read",  # 获取字段信息
            "base:field:update",  # 更新字段
            # 表单管理
            "base:form:read",  # 获取表单数据
            "base:form:update",  # 更新表单数据
            # 记录管理
            "base:record:create",  # 新增记录
            "base:record:delete",  # 删除记录
            "base:record:read",  # 检索特定记录
            "base:record:retrieve",  # 根据条件搜索记录
            "base:record:update",  # 更新记录
            # 角色管理
            "base:role:create",  # 新增自定义角色
            "base:role:delete",  # 删除自定义角色
            "base:role:read",  # 查询自定义角色
            "base:role:update",  # 更新自定义角色
            # 数据表管理
            "base:table:create",  # 新增数据表
            "base:table:delete",  # 删除数据表
            "base:table:read",  # 获取数据表信息
            "base:table:update",  # 更新数据表
            # 视图管理
            "base:view:read",  # 检索视图
            "base:view:write_only",  # 新增、更新或删除视图
        ],
        "PKCE_ENABLED": True,
    },
}

SERVER_HOST = os.getenv("SERVER_HOST", "http://localhost:8000")  # 用于生成回调URL

# Logging
# 日志处理器配置说明：
# 1. console - 控制台输出，开发环境使用
# 2. file - 文件日志，按天轮转
#    - 文件名格式: logs/django.log
#    - 每天午夜轮转
#    - UTF-8编码
#    - 保留天数：本地开发/测试环境3天，生产环境30天
# 根据 DEBUG 模式动态设置日志级别
LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

# 根据环境设置日志保留天数
# 生产环境（DEBUG=False）保留30天，开发/测试环境（DEBUG=True）保留3天
LOG_BACKUP_COUNT = 3 if DEBUG else 30

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "<%(pathname)s:%(lineno)d>\n[%(levelname)s] - %(asctime)s\n======%(funcName)s======\n%(message)s\n",
            "datefmt": "%Y-%m-%d %H:%M:%S %z",
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",  # Handler 级别设为 DEBUG，让 logger 级别控制
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "level": "DEBUG",  # Handler 级别设为 DEBUG，让 logger 级别控制
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/django.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": LOG_BACKUP_COUNT,
            "formatter": "standard",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # Django 框架和依赖包 - 保持 INFO 级别，避免过多调试信息
        "django": {"handlers": ["console", "file"], "level": "INFO", "propagate": False},
        "django.utils.autoreload": {"handlers": ["console", "file"], "level": "WARNING", "propagate": False},  # 屏蔽 autoreload 的 DEBUG 消息
        "django.db.backends": {"handlers": ["console", "file"], "level": "WARNING", "propagate": False},  # 屏蔽数据库查询日志
        
        # Celery 相关
        "celery": {"handlers": ["console", "file"], "level": "WARNING", "propagate": False},
        "celery.worker.strategy": {"handlers": ["console", "file"], "level": "WARNING", "propagate": False},
        "celery.app.trace": {"handlers": ["console", "file"], "level": "WARNING", "propagate": False},
        
        # 项目应用 - DEBUG 模式下显示 DEBUG 消息
        "webapps": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        "agentic": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        "llm": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        "knowledge": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        "tools": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        "authentication": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        "payment": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        "customized": {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False},
        
        # Root logger - 捕获其他所有日志（第三方库等），保持 INFO 级别
        "": {
            "handlers": ["console", "file"],
            "level": "INFO",  # 第三方库默认 INFO 级别
        }
    },
}

# Celery Configuration
# ------------------------------------------------------------------------------
# 使用 Redis 作为消息代理 (推荐用于生产和开发环境)
# 建议为 Celery 单独使用一个 Redis DB，例如 DB 0
# 建议为 Celery 单独使用一个 Redis DB，例如 DB 0
CELERY_DB = os.getenv("CELERY_DB", "0")
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{CELERY_DB}"
if REDIS_PASSWORD:
    # 使用 URL 编码后的密码构建连接字符串
    CELERY_BROKER_URL = f"redis://:{REDIS_PASSWORD_QUOTED}@{REDIS_HOST}:{REDIS_PORT}/{CELERY_DB}"
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}  # 1 hour

# 结果后端改用 Redis（推荐方案：自动过期，性能更好）
# 使用不同的 Redis DB（2）来存储结果，避免与 Broker（DB 0）混淆
CELERY_RESULT_DB = os.getenv("CELERY_RESULT_DB", "2")
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/{CELERY_RESULT_DB}"
if REDIS_PASSWORD:
    CELERY_RESULT_BACKEND = f"redis://:{REDIS_PASSWORD_QUOTED}@{REDIS_HOST}:{REDIS_PORT}/{CELERY_RESULT_DB}"

# 如果需要继续使用数据库存储（不推荐），取消下面的注释：
# CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery 优化配置（支持高并发）
# 固定使用 gevent 池配置
# CELERY_WORKER_POOL = 'gevent'  # 使用 -P gevent 命令行参数代替
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # 定期回收 worker
CELERY_BROKER_POOL_LIMIT = None  # 禁用连接池限制
CELERY_RESULT_BACKEND_POOL_LIMIT = None
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # 增加预取，提高任务处理效率（170 QPS）

# Celery 结果过期配置
CELERY_RESULT_EXPIRES = 86400  # 24小时后自动过期（Redis 会自动清理）
# 注：使用 Redis 后端时，过期的结果会自动被 Redis 清理，无需手动干预

# Celery 队列配置
# ------------------------------------------------------------------------------
# 定义队列配置（所有队列共享同一个 broker DB）
from kombu import Queue, Exchange

CELERY_TASK_QUEUES = (
    # 默认队列：处理一般任务
    Queue('celery', Exchange('celery'), routing_key='celery',
          queue_arguments={'x-max-priority': 10}),

    # PDF Extractor 队列：处理 PDF 提取任务
    Queue('pdf_extractor', Exchange('pdf_extractor'), routing_key='pdf_extractor',
          queue_arguments={'x-max-priority': 10}),
)

# 任务路由配置：将特定任务路由到指定队列
CELERY_TASK_ROUTES = {
    # PDF Extractor 相关任务路由到 pdf_extractor 队列
    'toolkit.process_pdf_extraction': {
        'queue': 'pdf_extractor',
        'routing_key': 'pdf_extractor',
    },
    'toolkit.cleanup_old_tasks': {
        'queue': 'pdf_extractor',
        'routing_key': 'pdf_extractor',
    },
}

# 默认队列
CELERY_TASK_DEFAULT_QUEUE = 'celery'
CELERY_TASK_DEFAULT_EXCHANGE = 'celery'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'celery'

# Celery Beat 定时任务配置
CELERY_BEAT_SCHEDULE = {
    'check-and-flush-callbacks': {
        'task': 'customized.image_editor.tasks_batch.check_and_flush_callbacks',
        'schedule': 3.0,  # 每3秒检查一次
        'options': {'queue': 'celery'}
    },
    'cleanup-stuck-callbacks': {
        'task': 'customized.image_editor.tasks_batch.cleanup_stuck_callbacks',
        'schedule': 300.0,  # 每5分钟清理一次
        'options': {'queue': 'celery'}
    },
    'check-download-heartbeat': {
        'task': 'dataset_downloader.tasks.check_heartbeat_timeout',
        'schedule': 60.0,
        'options': {'queue': 'celery'}
    }
}

# MinerU 配置
MINERU_SETTINGS = {
    'OUTPUT_DIR': os.path.join(BASE_DIR, 'mineru', 'outputs'),
    'UPLOAD_DIR': os.path.join(BASE_DIR, 'mineru', 'uploads'),
    'TEMP_DIR': os.path.join(BASE_DIR, 'mineru', 'temp'),
    'MAX_FILE_SIZE': 100 * 1024 * 1024,  # 100MB
    'ALLOWED_FILE_TYPES': ['pdf', 'jpg', 'png', 'doc', 'docx', 'ppt', 'pptx'],
    'GPU_ENABLED': GPU_AVAILABLE,
    'MODEL_SOURCE': os.getenv('MINERU_MODEL_SOURCE', 'local'),
    # MinerU v2.2 新特性
    'ENABLE_TABLE_MERGE': True,  # 启用跨页表格合并
    'USE_NEW_TABLE_MODEL': True,  # 使用新的表格识别模型
    'SUPPORT_LANGUAGES': ['en', 'zh', 'th', 'el'],  # v2.2新增: 泰语和希腊语OCR支持
    # 存储优化配置
    'USE_OSS': os.getenv('MINERU_USE_OSS', 'true').lower() == 'true',  # 启用 OSS 存储
    'CACHE_ENABLED': True,  # 启用缓存
    'CACHE_EXPIRE_DAYS': 7,  # 缓存过期天数
}

# WhiteNoise 配置
# 启用静态文件压缩和缓存
WHITENOISE_AUTOREFRESH = DEBUG  # 开发环境自动刷新
WHITENOISE_USE_FINDERS = DEBUG  # 开发环境从 STATICFILES_DIRS 查找文件
WHITENOISE_COMPRESS_OFFLINE = not DEBUG  # 生产环境启用压缩

# Payment 支付模块配置
BACKEND_API_URL = os.getenv('SERVER_HOST', 'http://localhost:8000')

PAYMENT_SETTINGS = {
    # 后端地址配置（用于异步回调通知）
    'BACKEND_API_URL': BACKEND_API_URL,
    
    # 支付订单默认过期时间（分钟）
    'ORDER_EXPIRE_MINUTES': int(os.getenv('PAYMENT_ORDER_EXPIRE_MINUTES', '30')),
    
    # 虎皮椒支付配置（可通过环境变量覆盖，也可在数据库中配置）
    'HUPIJIAO': {
        'APP_ID': os.getenv('HUPIJIAO_APP_ID', ''),
        'APP_SECRET': os.getenv('HUPIJIAO_APP_SECRET', ''),
        'API_URL': os.getenv('HUPIJIAO_API_URL', 'https://api.xunhupay.com/payment/do.html'),
        'TEST_MODE': os.getenv('HUPIJIAO_TEST_MODE', 'True').lower() == 'true',
    },
    
    # 支付日志级别
    'LOG_LEVEL': os.getenv('PAYMENT_LOG_LEVEL', 'INFO'),
}

# Email Configuration
# ------------------------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
# QQ企业邮箱使用SSL，端口465
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# 邮箱验证码配置
EMAIL_VERIFICATION_CODE_LENGTH = 6
EMAIL_VERIFICATION_CODE_EXPIRE_MINUTES = 10

# 站点信息
SITE_NAME = os.getenv('SITE_NAME', 'Agentic AI Platform')
