# Generated by Django 5.2.8 on 2026-01-19 08:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Recipe 唯一标识符（如 twitter-login）', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_recipe_name', message='Recipe 名称只能包含小写字母、数字和连字符', regex='^[a-z0-9-]+$')], verbose_name='名称')),
                ('description', models.TextField(help_text='Recipe 功能描述', verbose_name='描述')),
                ('runtime', models.CharField(choices=[('chrome-js', 'Chrome CDP JavaScript'), ('python', 'Python 脚本'), ('shell', 'Shell 脚本')], max_length=20, verbose_name='运行时类型')),
                ('is_public', models.BooleanField(default=True, help_text='是否在市场中公开可见', verbose_name='是否公开')),
                ('is_premium', models.BooleanField(default=False, help_text='是否需要 VIP/Enterprise 订阅才能下载', verbose_name='是否需要订阅')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='冗余字段，异步计算更新', max_digits=3, verbose_name='平均评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-download_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 星评分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='market.recipe', verbose_name='Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Recipe 评分',
                'verbose_name_plural': 'Recipe 评分',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='语义版本号（如 1.0.0）', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_version', message='版本号必须是语义版本格式（如 1.0.0）', regex='^\\d+\\.\\d+\\.\\d+$')], verbose_name='版本号')),
                ('content', models.TextField(help_text='Recipe 脚本内容', verbose_name='内容')),
                ('changelog', models.TextField(blank=True, default='', verbose_name='更新说明')),
                ('is_latest', models.BooleanField(default=False, verbose_name='是否最新版本')),
                ('file_size', models.PositiveIntegerField(help_text='字节数', verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='market.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'Recipe 版本',
                'verbose_name_plural': 'Recipe 版本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='本地会话 ID')),
                ('name', models.CharField(blank=True, default='', help_text='用户自定义名称', max_length=200, verbose_name='会话名称')),
                ('agent_type', models.CharField(max_length=50, verbose_name='Agent 类型')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元信息')),
                ('storage_key', models.CharField(help_text='R2 存储路径', max_length=200, verbose_name='存储路径')),
                ('file_size', models.PositiveIntegerField(help_text='字节数', verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '同步会话',
                'verbose_name_plural': '同步会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(help_text='CLI 轮询用', max_length=64, unique=True, verbose_name='设备码')),
                ('user_code', models.CharField(help_text='显示给用户的 8 位代码', max_length=8, unique=True, verbose_name='用户码')),
                ('client_id', models.CharField(max_length=100, verbose_name='客户端标识')),
                ('scope', models.CharField(default='market sync', max_length=200, verbose_name='授权范围')),
                ('status', models.CharField(choices=[('pending', '等待授权'), ('authorized', '已授权'), ('used', '已使用'), ('expired', '已过期'), ('denied', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('user', models.ForeignKey(blank=True, help_text='认证成功后关联的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_codes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '设备认证码',
                'verbose_name_plural': '设备认证码',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_code'], name='idx_device_code'), models.Index(fields=['user_code'], name='idx_user_code'), models.Index(fields=['expires_at'], name='idx_expires')],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='idx_recipe_name'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author'], name='idx_recipe_author'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_public', 'is_premium'], name='idx_recipe_public_premium'),
        ),
        migrations.AddIndex(
            model_name='reciperating',
            index=models.Index(fields=['recipe'], name='idx_rating_recipe'),
        ),
        migrations.AddIndex(
            model_name='reciperating',
            index=models.Index(fields=['user'], name='idx_rating_user'),
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('recipe', 'user')},
        ),
        migrations.AddIndex(
            model_name='recipeversion',
            index=models.Index(fields=['recipe', 'is_latest'], name='idx_version_recipe_latest'),
        ),
        migrations.AddIndex(
            model_name='recipeversion',
            index=models.Index(fields=['recipe', 'version'], name='idx_version_recipe_version'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeversion',
            unique_together={('recipe', 'version')},
        ),
        migrations.AddIndex(
            model_name='syncedsession',
            index=models.Index(fields=['user', '-created_at'], name='idx_session_user'),
        ),
        migrations.AlterUniqueTogether(
            name='syncedsession',
            unique_together={('user', 'session_id')},
        ),
    ]
