# Generated by Django 5.1.5 on 2025-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='服务器IP地址')),
                ('reason', models.CharField(max_length=2000, verbose_name='申请原因')),
                ('result', models.CharField(choices=[('审核中', '审核中'), ('通过', '通过'), ('驳回', '驳回')], default='审核中', max_length=100, verbose_name='审批结论')),
                ('task', models.CharField(default='合同审核', max_length=2000, verbose_name='业务名称')),
                ('llm_models', models.ManyToManyField(blank=True, related_name='llm_check', to='router.llmmodel', verbose_name='关联大语言模型')),
            ],
            options={
                'verbose_name': '用户模型审核',
                'verbose_name_plural': '用户模型审核',
            },
        ),
    ]
