# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('service_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginauth',
            name='service_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_api_check', to='service_api.externalservice', verbose_name='关联外部服务'),
        ),
        migrations.AddField(
            model_name='userloginauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_check', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
