# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_app', models.CharField(max_length=64, verbose_name='来源应用')),
                ('source_type', models.CharField(max_length=1000, verbose_name='来源类型')),
                ('task_id', models.TextField(blank=True, max_length=1000, null=True, verbose_name='任务Id')),
                ('input', models.JSONField(default=dict, verbose_name='原始输入')),
                ('prompt_text', models.TextField(blank=True, null=True, verbose_name='提示文本')),
                ('prompt_images', models.JSONField(blank=True, default=list, null=True, verbose_name='提示图片')),
                ('prompt_files', models.JSONField(blank=True, default=list, null=True, verbose_name='提示文件')),
                ('model', models.CharField(max_length=64, verbose_name='模型名称')),
                ('prompt_params', models.JSONField(blank=True, default=dict, null=True, verbose_name='提示参数')),
                ('origin_response', models.JSONField(default=dict, verbose_name='原始响应')),
                ('response', models.JSONField(default=dict, verbose_name='拼装后响应')),
                ('output', models.JSONField(default=dict, verbose_name='输出结果')),
                ('is_final', models.CharField(default='否', max_length=10, verbose_name='是否是最终结果')),
                ('input_session_length', models.PositiveIntegerField(default=0, verbose_name='输入文本长度 (Token)')),
                ('output_session_length', models.PositiveIntegerField(default=0, verbose_name='输出文本长度 (Token)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizedqas', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '定制化记录',
                'verbose_name_plural': '定制化记录',
            },
        ),
    ]
