# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEditorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='配置标识符，默认使用default', max_length=100, unique=True, verbose_name='配置名称')),
                ('default_prompt', models.TextField(default='完全参考图片内容, 调整图片风格变为油画刮刀风格，刮刀笔触适中，色彩饱满偏暖，姿态鲜活自然，必须使用纯白色背景#ffffff', help_text='当用户未提供提示词时使用的默认值', verbose_name='默认提示词')),
                ('use_random_seed', models.BooleanField(default=True, help_text='是否使用随机seed值，如果为False则使用fixed_seed', verbose_name='使用随机Seed')),
                ('fixed_seed', models.IntegerField(blank=True, help_text='当use_random_seed为False时使用的固定seed值', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='固定Seed值')),
                ('seed_min', models.IntegerField(default=100000000, help_text='生成随机seed的最小值', validators=[django.core.validators.MinValueValidator(1)], verbose_name='随机Seed最小值')),
                ('seed_max', models.IntegerField(default=999999999, help_text='生成随机seed的最大值', validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='随机Seed最大值')),
                ('guidance_scale', models.FloatField(default=10.0, help_text='图像生成的引导强度，值越大越接近提示词描述', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(30.0)], verbose_name='引导系数')),
                ('generation_model', models.CharField(default='doubao-seededit-3-0-i2i-250628', help_text='用于图像生成的模型名称', max_length=100, verbose_name='生成模型')),
                ('detection_model', models.CharField(default='doubao-1.5-vision-pro-250328', help_text='用于宠物检测的模型名称', max_length=100, verbose_name='检测模型')),
                ('detection_prompt', models.TextField(default='你必须分析图片并输出JSON格式的结果。\n\n<purpose>\n检测图片内容是否合规。特别注意：动物的交配、生殖、繁殖行为属于不合规内容。需要检测是否存在暴力、色情内容，以及图片内容的主体是否仅为动物（宠物）且不包含人类。\n如果图片合规，你必须生成极其详细和精确的宠物描述，用于文生图模型重建。\n</purpose>\n\n<options_for_false_reason>\n- A: 图片包含暴力内容\n- B: 图片包含色情内容（特别包括但不限于：动物交配、动物生殖器官展示、动物繁殖行为、动物求偶行为等）\n- C: 图片主体不是动物\n- D: 图片包含完整的人类面部或上半身躯干肢体\n- E: 图片质量过低（分辨率或清晰度不足）\n- F: 图片包含多个主体\n</options_for_false_reason>\n\n<pet_description_requirements>\n如果图片合规，你必须提供一个极其详细、精确的宠物描述，包含以下所有方面：\n\n1. **品种与体型**：准确的品种名称、体型大小、身材比例\n2. **毛发特征**：\n   - 毛发长度（短毛/中长毛/长毛）\n   - 毛发质地（直毛/卷毛/波浪毛、粗糙/柔软/丝滑）\n   - 毛发密度和蓬松程度\n3. **颜色与花纹**：\n   - 主色调和次要色调的精确描述\n   - 特殊花纹或斑点的位置、形状、大小\n   - 渐变色或混色区域的描述\n4. **面部特征**：\n   - 眼睛：颜色、大小、形状、神态\n   - 鼻子：颜色、湿润度\n   - 嘴巴：是否张开、舌头位置\n   - 耳朵：形状、位置、朝向（立耳/垂耳/半立）\n5. **姿态与动作**：\n   - 身体姿势（站立/坐姿/卧姿/奔跑/跳跃等）\n   - 头部朝向和角度\n   - 四肢位置和动作\n   - 尾巴位置和状态（上翘/下垂/摇摆等）\n6. **特殊细节**：\n   - 任何独特的标记或特征（如额头的星形斑、脚掌的白袜等）\n   - 配饰（项圈、铃铛、衣服等）的颜色、材质、样式\n   - 表情和情绪状态（警觉/放松/兴奋/好奇等）\n\n描述要求：\n- 使用精确、具体的词汇\n- 按照从整体到局部、从主要到次要的顺序\n- 包含所有可见的细节特征\n- 描述长度：150-250字\n</pet_description_requirements>\n\n<output_rules>\n你的输出必须是一个有效的JSON对象。不要输出任何其他内容，只输出JSON。\nJSON必须包含以下三个字段（缺一不可）：\n1. "object_is_only_animal": boolean类型 - 是否仅包含动物（宠物）且合规\n2. "reason_for_false": string类型或null - 如果不合规，必须提供原因代码（A-F）；如果合规，必须为null\n3. "pet_description": string类型或null - 如果合规，必须提供150-250字的极其详细的宠物描述；如果不合规，必须为null\n\n重要：当object_is_only_animal为true时，pet_description字段必须包含详细的宠物描述，不能为null或空字符串！\n\n示例输出（合规情况，注意pet_description必须有内容）：\n{\n    "object_is_only_animal": true,\n    "reason_for_false": null,\n    "pet_description": "一只成年雄性金毛寻回犬，体型中大，身材匀称健壮。拥有中长度的金棕色直毛，毛发浓密蓬松，呈现出温暖的蜂蜜色光泽。面部特征鲜明：深棕色的大眼睛流露出温和友善的神情，黑色湿润的鼻子，粉红色的舌头微微外露。耳朵呈三角形自然下垂，紧贴头部两侧。此刻正以坐姿端正，前腿笔直支撑，后腿自然弯曲，尾巴自然下垂，尾尖的毛发略长呈羽毛状。颈部佩戴一条深蓝色的尼龙项圈，项圈上有银色的金属扣环。整体表情放松愉悦，嘴角微微上扬呈现微笑状。"\n}\n\n示例输出（不合规情况）：\n{\n    "object_is_only_animal": false,\n    "reason_for_false": "D",\n    "pet_description": null\n}\n</output_rules>\n\n现在请分析图片，并严格按照上述要求输出JSON。记住：如果图片是合规的宠物图片，你必须在pet_description字段中提供150-300字的详细描述，不能返回null！', help_text='用于宠物检测的提示词，必须包含pet_description字段的要求', verbose_name='宠物检测提示词')),
                ('style_prompt', models.TextField(default='油画刮刀风格，刮刀笔触适中，色彩饱满偏暖，姿态鲜活自然，纯白色背景#ffffff', help_text='用于文生图的风格化要求，会与宠物描述结合使用', verbose_name='风格化提示词')),
                ('t2i_model', models.CharField(default='doubao-seedream-3-0-t2i-250415', help_text='用于文本生成图像的模型名称', max_length=100, verbose_name='文生图模型')),
                ('t2i_size', models.CharField(default='1024x1024', help_text='文生图输出尺寸，支持：1024x1024, 1024x768, 768x1024等', max_length=50, verbose_name='文生图尺寸')),
                ('t2i_guidance_scale', models.FloatField(default=7.5, help_text='文生图的引导强度，值越大越接近文本描述', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='文生图引导系数')),
                ('image_size', models.CharField(default='adaptive', help_text='生成图像的尺寸，如1024x1024或adaptive', max_length=50, verbose_name='图像尺寸')),
                ('add_watermark', models.BooleanField(default=False, help_text='是否在生成的图像上添加水印', verbose_name='添加水印')),
                ('response_format', models.CharField(choices=[('url', 'URL'), ('b64_json', 'Base64')], default='url', help_text='API返回的图像格式', max_length=20, verbose_name='响应格式')),
                ('api_timeout', models.IntegerField(default=60, help_text='API调用的超时时间（秒）', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)], verbose_name='API超时时间')),
                ('max_retries', models.IntegerField(default=3, help_text='API调用失败时的最大重试次数', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='最大重试次数')),
                ('enable_bg_removal', models.BooleanField(default=True, help_text='是否启用背景移除功能', verbose_name='启用背景移除')),
                ('bg_removal_max_retries', models.IntegerField(default=3, help_text='背景移除失败时的最大重试次数', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='背景移除最大重试次数')),
                ('is_active', models.BooleanField(default=True, help_text='只有激活的配置才会被使用', verbose_name='配置是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图片编辑器配置',
                'verbose_name_plural': '图片编辑器配置',
                'db_table': 'image_editor_config',
            },
        ),
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='批量回调地址')),
                ('total_count', models.IntegerField(verbose_name='总任务数')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '批量任务',
                'verbose_name_plural': '批量任务',
                'db_table': 'image_edit_batch_task',
            },
        ),
        migrations.CreateModel(
            name='ImageEditTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(verbose_name='风格描述提示词')),
                ('image_url', models.URLField(max_length=500, verbose_name='原始图片URL')),
                ('callback_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='回调地址')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('success', '成功'), ('failed', '失败')], default='processing', max_length=20)),
                ('result_image', models.TextField(blank=True, null=True, verbose_name='处理后的图片base64')),
                ('result_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='处理后的图片文件路径')),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, max_length=10, null=True, verbose_name='图片格式')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='图片宽度')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='图片高度')),
                ('image_size_bytes', models.IntegerField(blank=True, null=True, verbose_name='图片大小(字节)')),
                ('image_aspect_ratio', models.FloatField(blank=True, null=True, verbose_name='图片宽高比')),
                ('pet_detection_result', models.BooleanField(blank=True, null=True, verbose_name='是否为宠物')),
                ('pet_detection_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='检测失败原因')),
                ('pet_detection_model', models.CharField(blank=True, default='doubao-1.5-vision-pro-250328', max_length=50, null=True, verbose_name='检测模型')),
                ('pet_description', models.TextField(blank=True, null=True, verbose_name='宠物描述')),
                ('generation_model', models.CharField(blank=True, default='doubao-seededit-3-0-i2i-250628', max_length=50, null=True, verbose_name='生成模型')),
                ('generation_seed', models.IntegerField(blank=True, null=True, verbose_name='生成seed值')),
                ('generation_guidance_scale', models.FloatField(blank=True, default=10, null=True, verbose_name='引导系数')),
                ('actual_prompt', models.TextField(blank=True, null=True, verbose_name='实际使用的提示词')),
                ('generated_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='生成的图片URL')),
                ('consistency_check', models.BooleanField(blank=True, null=True, verbose_name='一致性检测是否通过')),
                ('consistency_score', models.FloatField(blank=True, null=True, verbose_name='一致性分数')),
                ('consistency_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='不一致原因')),
                ('bg_removal_attempted', models.BooleanField(default=False, verbose_name='是否尝试背景移除')),
                ('bg_removal_success', models.BooleanField(blank=True, null=True, verbose_name='背景移除是否成功')),
                ('bg_removal_retry_count', models.IntegerField(default=0, verbose_name='背景移除重试次数')),
                ('bg_removal_error', models.TextField(blank=True, null=True, verbose_name='背景移除错误信息')),
                ('bg_removed_source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='用于背景移除的原图URL')),
                ('image_validation_duration', models.FloatField(blank=True, null=True, verbose_name='图片验证时长(秒)')),
                ('pet_detection_duration', models.FloatField(blank=True, null=True, verbose_name='宠物检测时长(秒)')),
                ('text_to_image_duration', models.FloatField(blank=True, null=True, verbose_name='文生图时长(秒)')),
                ('consistency_check_duration', models.FloatField(blank=True, null=True, verbose_name='一致性检测时长(秒)')),
                ('bg_removal_duration', models.FloatField(blank=True, null=True, verbose_name='背景移除时长(秒)')),
                ('callback_duration', models.FloatField(blank=True, null=True, verbose_name='回调发送时长(秒)')),
                ('callback_status', models.CharField(choices=[('pending', '待发送'), ('success', '成功'), ('failed', '失败'), ('not_required', '无需回调')], default='pending', max_length=20, verbose_name='回调状态')),
                ('callback_attempts', models.IntegerField(default=0, verbose_name='回调尝试次数')),
                ('callback_occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='回调发生时间')),
                ('callback_response_code', models.IntegerField(blank=True, null=True, verbose_name='回调响应状态码')),
                ('callback_error_message', models.TextField(blank=True, default='', verbose_name='回调错误信息')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_edit_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '图片编辑任务',
                'verbose_name_plural': '图片编辑任务',
                'db_table': 'image_edit_task',
                'indexes': [models.Index(fields=['created_at'], name='image_edit__created_ac163b_idx'), models.Index(fields=['status'], name='image_edit__status_c7ad84_idx'), models.Index(fields=['user', 'created_at'], name='image_edit__user_id_d6e105_idx')],
            },
        ),
    ]
