# Generated by Django 5.2.8 on 2025-12-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomentsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=64, unique=True, verbose_name='帖子ID')),
                ('author_open_id', models.CharField(blank=True, max_length=64, verbose_name='发帖人OpenID')),
                ('author_user_id', models.CharField(blank=True, max_length=64, verbose_name='发帖人UserID')),
                ('content_raw', models.JSONField(default=list, verbose_name='原始富文本内容')),
                ('content_text', models.TextField(blank=True, verbose_name='解析后的纯文本')),
                ('category_ids', models.JSONField(default=list, verbose_name='板块ID列表')),
                ('feishu_create_time', models.DateTimeField(null=True, verbose_name='飞书发帖时间')),
                ('event_id', models.CharField(blank=True, max_length=64, verbose_name='事件ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
            ],
            options={
                'verbose_name': '公司圈帖子',
                'verbose_name_plural': '公司圈帖子',
                'db_table': 'moments_post',
                'ordering': ['-feishu_create_time'],
            },
        ),
    ]
