# Generated by Django 5.2.8 on 2025-12-29 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='监控关键词')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高', verbose_name='优先级')),
                ('match_type', models.CharField(choices=[('exact', '精确匹配'), ('contains', '包含匹配'), ('regex', '正则匹配')], default='contains', max_length=20, verbose_name='匹配方式')),
                ('category', models.CharField(blank=True, help_text='用于对关键词进行分组管理', max_length=50, verbose_name='分类标签')),
                ('description', models.TextField(blank=True, verbose_name='描述说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xhs_keywords_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '监控关键词',
                'verbose_name_plural': '监控关键词',
                'db_table': 'xiaohongshu_monitor_keyword',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XiaohongshuNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(help_text='小红书笔记唯一标识', max_length=64, unique=True, verbose_name='笔记ID')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='作者昵称')),
                ('author_avatar', models.URLField(blank=True, max_length=500, verbose_name='作者头像')),
                ('description', models.TextField(blank=True, verbose_name='笔记正文内容')),
                ('note_type', models.CharField(choices=[('image', '图文笔记'), ('video', '视频笔记')], default='image', max_length=20, verbose_name='笔记类型')),
                ('images', models.JSONField(default=list, help_text='图片URL数组', verbose_name='图片列表')),
                ('tags', models.JSONField(default=list, help_text='标签列表如 #霸王茶姬', verbose_name='标签列表')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collects_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('publish_time', models.CharField(blank=True, help_text='如"编辑于"、"14分钟前"', max_length=50, verbose_name='发布时间描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='发布位置')),
                ('top_comments', models.JSONField(default=list, verbose_name='热评列表')),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name='采集时间')),
                ('card_index', models.IntegerField(default=0, verbose_name='采集卡片索引')),
                ('source', models.CharField(blank=True, help_text='采集客户端标识', max_length=50, verbose_name='数据来源')),
                ('raw_data', models.JSONField(default=dict, help_text='采集到的原始JSON数据', verbose_name='原始数据')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('analyzing', '分析中'), ('completed', '已完成'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('matched_keywords', models.ManyToManyField(blank=True, related_name='matched_notes', to='xiaohongshu.monitorkeyword', verbose_name='命中的关键词')),
            ],
            options={
                'verbose_name': '小红书笔记',
                'verbose_name_plural': '小红书笔记',
                'db_table': 'xiaohongshu_note',
                'ordering': ['-extracted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('category_1', '类别1 - 负面舆情客诉'), ('category_2', '类别2 - 数据泄露风险'), ('category_3', '类别3 - 黑灰产信息'), ('category_4', '类别4 - 代下单'), ('other', '其他 - 非负面')], default='other', max_length=20, verbose_name='分析类别')),
                ('sentiment', models.CharField(choices=[('positive', '正向'), ('neutral', '中立'), ('negative', '负向')], default='neutral', max_length=20, verbose_name='情感倾向')),
                ('risk_score', models.IntegerField(default=50, help_text='0-100分，分数越高风险越大', verbose_name='风险评分')),
                ('reason', models.TextField(blank=True, help_text='AI给出的分类原因说明', verbose_name='分析原因')),
                ('image_analysis', models.JSONField(default=list, help_text='每张图片的VLM分析结果', verbose_name='图片分析结果')),
                ('llm_response', models.JSONField(default=dict, verbose_name='LLM原始响应')),
                ('model_used', models.CharField(blank=True, max_length=100, verbose_name='使用的模型')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='输入Token数')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='输出Token数')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('analysis_duration', models.FloatField(default=0, verbose_name='分析耗时(秒)')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='是否已人工复核')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('review_notes', models.TextField(blank=True, verbose_name='复核备注')),
                ('manual_category', models.CharField(blank=True, choices=[('category_1', '类别1 - 负面舆情客诉'), ('category_2', '类别2 - 数据泄露风险'), ('category_3', '类别3 - 黑灰产信息'), ('category_4', '类别4 - 代下单'), ('other', '其他 - 非负面')], max_length=20, verbose_name='人工修正类别')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xhs_reviews', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='xiaohongshu.xiaohongshunote', verbose_name='关联笔记')),
            ],
            options={
                'verbose_name': '笔记分析结果',
                'verbose_name_plural': '笔记分析结果',
                'db_table': 'xiaohongshu_note_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitorkeyword',
            index=models.Index(fields=['keyword', 'is_active'], name='xiaohongshu_keyword_919be4_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorkeyword',
            index=models.Index(fields=['category'], name='xiaohongshu_categor_19a20c_idx'),
        ),
        migrations.AddIndex(
            model_name='xiaohongshunote',
            index=models.Index(fields=['note_id'], name='xiaohongshu_note_id_1d6bae_idx'),
        ),
        migrations.AddIndex(
            model_name='xiaohongshunote',
            index=models.Index(fields=['status'], name='xiaohongshu_status_bc4848_idx'),
        ),
        migrations.AddIndex(
            model_name='xiaohongshunote',
            index=models.Index(fields=['extracted_at'], name='xiaohongshu_extract_6a51bc_idx'),
        ),
        migrations.AddIndex(
            model_name='xiaohongshunote',
            index=models.Index(fields=['created_at'], name='xiaohongshu_created_148b69_idx'),
        ),
        migrations.AddIndex(
            model_name='noteanalysisresult',
            index=models.Index(fields=['category'], name='xiaohongshu_categor_257baa_idx'),
        ),
        migrations.AddIndex(
            model_name='noteanalysisresult',
            index=models.Index(fields=['sentiment'], name='xiaohongshu_sentime_afaa44_idx'),
        ),
        migrations.AddIndex(
            model_name='noteanalysisresult',
            index=models.Index(fields=['risk_score'], name='xiaohongshu_risk_sc_c2e55a_idx'),
        ),
        migrations.AddIndex(
            model_name='noteanalysisresult',
            index=models.Index(fields=['is_reviewed'], name='xiaohongshu_is_revi_bddfe8_idx'),
        ),
    ]
