# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会话ID')),
                ('ai_conversation_id', models.CharField(max_length=255, verbose_name='AI会话ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='会话标题')),
                ('last_message_preview', models.CharField(blank=True, max_length=200, null=True, verbose_name='最后消息预览')),
                ('last_interacted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后交互时间')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('files_info', models.JSONField(blank=True, null=True, verbose_name='文件信息')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务ID')),
                ('task_steps', models.JSONField(blank=True, null=True, verbose_name='任务步骤')),
                ('final_web_search_results', models.JSONField(blank=True, null=True, verbose_name='网页搜索结果')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('task_steps_compressed', models.TextField(blank=True, help_text='Base64编码的gzip压缩数据', null=True, verbose_name='压缩的任务步骤')),
                ('use_compression', models.BooleanField(default=False, verbose_name='是否使用压缩存储')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记，已删除的消息不会显示给用户但数据仍保留', verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-last_interacted_at'], name='chat_chatse_user_id_9aee0a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['last_interacted_at'], name='chat_chatse_last_in_8e646b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('user', 'ai_conversation_id')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session'], name='chat_chatme_session_cfafa5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_chatme_created_888e17_idx'),
        ),
    ]
