# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('router', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagtiveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置集的唯一名称', max_length=100, unique=True, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, help_text='描述该配置集的用途', verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=False, help_text='当前是否为激活配置（系统只能有一套激活配置）', verbose_name='是否激活')),
                ('system_prompt', models.TextField(blank=True, help_text='覆盖默认系统提示词（可选）', verbose_name='系统提示词')),
                ('generate_template', models.TextField(blank=True, help_text='覆盖默认生成页面提示词模板（可选）', verbose_name='生成页面模板')),
                ('edit_template', models.TextField(blank=True, help_text='覆盖默认编辑页面提示词模板（可选）', verbose_name='编辑页面模板')),
                ('temperature', models.FloatField(default=0.7, help_text='控制生成的随机性（0-2）', verbose_name='Temperature参数')),
                ('max_tokens', models.IntegerField(blank=True, help_text='生成内容的最大令牌数（留空表示无限制）', null=True, verbose_name='最大令牌数')),
                ('enable_stream', models.BooleanField(default=False, help_text='是否启用流式响应', verbose_name='启用流式输出')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='其他JSON格式的配置参数', null=True, verbose_name='额外配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('llm_model', models.ForeignKey(blank=True, help_text='用于页面生成的默认LLM模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagtive_configs', to='router.llmmodel', verbose_name='默认LLM模型')),
                ('llm_model_for_edit', models.ForeignKey(blank=True, help_text='用于页面编辑的LLM模型（可选，不设置则使用默认模型）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagtive_edit_configs', to='router.llmmodel', verbose_name='编辑模式LLM模型')),
            ],
            options={
                'verbose_name': 'Pagtive配置',
                'verbose_name_plural': 'Pagtive配置',
                'db_table': 'webapps_pagtive_config',
            },
        ),
        migrations.CreateModel(
            name='PagtivePromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('system', '系统提示词'), ('generate', '生成页面'), ('edit', '编辑页面'), ('metadata', '元数据生成'), ('style', '样式生成'), ('custom', '自定义')], max_length=20, verbose_name='模板类型')),
                ('template_content', models.TextField(help_text='提示词模板内容，支持变量替换如 {{variable}}', verbose_name='模板内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('variables', models.JSONField(blank=True, default=list, help_text='模板中使用的变量名列表', null=True, verbose_name='变量列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='pagtive.pagtiveconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': 'Pagtive提示词模板',
                'verbose_name_plural': 'Pagtive提示词模板',
                'db_table': 'webapps_pagtive_prompt_templates',
                'ordering': ['config', 'template_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('project_style', models.TextField(blank=True, null=True, verbose_name='项目风格')),
                ('global_style_code', models.TextField(blank=True, null=True, verbose_name='全局样式代码')),
                ('pages', models.JSONField(blank=True, null=True, verbose_name='页面配置')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('style_tags', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None, verbose_name='风格标签')),
                ('batch_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='批次ID')),
                ('batch_index', models.IntegerField(blank=True, null=True, verbose_name='批次索引')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('reference_files', models.JSONField(blank=True, default=list, help_text='存储上传文件的OSS路径和元信息', verbose_name='参考文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'webapps_pagtive_projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(verbose_name='页面ID')),
                ('script', models.TextField(blank=True, null=True, verbose_name='脚本')),
                ('styles', models.TextField(blank=True, null=True, verbose_name='样式')),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML内容')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='图片')),
                ('mermaid_content', models.TextField(blank=True, null=True, verbose_name='Mermaid内容')),
                ('version_id', models.UUIDField(blank=True, null=True, verbose_name='版本ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pagtive.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目详情',
                'verbose_name_plural': '项目详情',
                'db_table': 'webapps_pagtive_project_details',
            },
        ),
        migrations.CreateModel(
            name='ProjectLLMLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='日志ID')),
                ('page_id', models.IntegerField(blank=True, null=True, verbose_name='页面ID')),
                ('provider', models.CharField(max_length=50, verbose_name='提供商')),
                ('model', models.CharField(max_length=100, verbose_name='模型')),
                ('scenario', models.CharField(blank=True, max_length=100, null=True, verbose_name='场景')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('request_prompts', models.JSONField(verbose_name='请求提示词')),
                ('request_config', models.JSONField(verbose_name='请求配置')),
                ('response_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('response_content', models.TextField(blank=True, null=True, verbose_name='响应内容')),
                ('response_error', models.TextField(blank=True, null=True, verbose_name='响应错误')),
                ('usage_prompt_tokens', models.IntegerField(blank=True, null=True, verbose_name='提示词令牌数')),
                ('usage_completion_tokens', models.IntegerField(blank=True, null=True, verbose_name='完成令牌数')),
                ('usage_total_tokens', models.IntegerField(blank=True, null=True, verbose_name='总令牌数')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='状态')),
                ('temporary_page_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='临时页面ID')),
                ('version_id', models.UUIDField(blank=True, help_text='关联的页面版本ID', null=True, verbose_name='关联版本ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='pagtive.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_llm_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目LLM日志',
                'verbose_name_plural': '项目LLM日志',
                'db_table': 'webapps_pagtive_llmlog',
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='协议ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='协议内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户协议',
                'verbose_name_plural': '用户协议',
                'db_table': 'webapps_pagtive_user_agreements',
                'indexes': [models.Index(fields=['version'], name='webapps_pag_version_93e4a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='邀请码ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='邀请码')),
                ('status', models.CharField(choices=[('available', '可用'), ('used', '已使用'), ('expired', '已过期')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('used_by_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_code', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'db_table': 'webapps_pagtive_invitation_codes',
                'indexes': [models.Index(fields=['status'], name='webapps_pag_status_2f396e_idx'), models.Index(fields=['code'], name='webapps_pag_code_e0c684_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pagtiveconfig',
            index=models.Index(fields=['is_active'], name='webapps_pag_is_acti_68f92e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagtiveconfig',
            index=models.Index(fields=['name'], name='webapps_pag_name_381a0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagtiveprompttemplate',
            unique_together={('config', 'name')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='webapps_pag_user_id_a45068_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_public'], name='webapps_pag_is_publ_1e1a96_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured'], name='webapps_pag_is_feat_53797b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published'], name='webapps_pag_is_publ_25d761_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdetail',
            unique_together={('project', 'page_id')},
        ),
        migrations.AddIndex(
            model_name='projectllmlog',
            index=models.Index(fields=['user'], name='webapps_pag_user_id_e4e458_idx'),
        ),
        migrations.AddIndex(
            model_name='projectllmlog',
            index=models.Index(fields=['project'], name='webapps_pag_project_3fdee9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectllmlog',
            index=models.Index(fields=['temporary_page_id'], name='webapps_pag_tempora_7ae60a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectllmlog',
            index=models.Index(fields=['provider', 'model'], name='webapps_pag_provide_61051b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectllmlog',
            index=models.Index(fields=['-request_timestamp'], name='webapps_pag_request_b94a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectllmlog',
            index=models.Index(fields=['status'], name='webapps_pag_status_9a8f47_idx'),
        ),
    ]
