# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFParseTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('png', 'PNG'), ('doc', 'DOC'), ('docx', 'DOCX'), ('ppt', 'PPT'), ('pptx', 'PPTX')], max_length=10, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小（字节）')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件存储路径')),
                ('parse_method', models.CharField(choices=[('auto', '自动'), ('ocr', 'OCR'), ('txt', '文本')], default='auto', max_length=10, verbose_name='解析方法')),
                ('debug_enabled', models.BooleanField(default=False, verbose_name='调试模式')),
                ('enable_table_merge', models.BooleanField(default=True, verbose_name='启用跨页表格合并')),
                ('use_new_table_model', models.BooleanField(default=True, verbose_name='使用新表格识别模型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('output_dir', models.CharField(blank=True, max_length=500, null=True, verbose_name='输出目录')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间（秒）')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('text_preview', models.TextField(blank=True, null=True, verbose_name='文本预览')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'PDF解析任务',
                'verbose_name_plural': 'PDF解析任务',
                'db_table': 'mineru_pdf_parse_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Markdown文件路径')),
                ('json_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='JSON文件路径')),
                ('total_text_blocks', models.IntegerField(default=0, verbose_name='文本块总数')),
                ('total_images', models.IntegerField(default=0, verbose_name='图片总数')),
                ('total_tables', models.IntegerField(default=0, verbose_name='表格总数')),
                ('total_formulas', models.IntegerField(default=0, verbose_name='公式总数')),
                ('cross_page_tables', models.IntegerField(default=0, verbose_name='跨页表格数')),
                ('metadata', models.JSONField(default=dict, verbose_name='其他元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='mineru.pdfparsetask', verbose_name='解析任务')),
            ],
            options={
                'verbose_name': '解析结果',
                'verbose_name_plural': '解析结果',
                'db_table': 'mineru_parse_result',
            },
        ),
    ]
