# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='对应 router.LLMModel.name', max_length=128, verbose_name='模型名称')),
                ('vendor_name', models.CharField(blank=True, max_length=128, verbose_name='供应商名称')),
                ('input_price_per_1k', models.DecimalField(decimal_places=6, help_text='每1000个输入Token的价格', max_digits=10, verbose_name='输入价格(每1K Token)')),
                ('output_price_per_1k', models.DecimalField(decimal_places=6, help_text='每1000个输出Token的价格', max_digits=10, verbose_name='输出价格(每1K Token)')),
                ('currency', models.CharField(choices=[('USD', '美元'), ('CNY', '人民币'), ('EUR', '欧元')], default='USD', max_length=3, verbose_name='货币单位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='生效日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM模型定价',
                'verbose_name_plural': 'LLM模型定价',
                'db_table': 'llm_model_price',
                'ordering': ['model_name', '-effective_date'],
                'indexes': [models.Index(fields=['model_name', 'is_active'], name='llm_model_p_model_n_8814a1_idx'), models.Index(fields=['vendor_name', 'model_name'], name='llm_model_p_vendor__d90a67_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMRequestCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='基于请求参数生成的唯一键', max_length=255, unique=True, verbose_name='缓存键')),
                ('model_name', models.CharField(db_index=True, max_length=128, verbose_name='模型名称')),
                ('request_hash', models.CharField(db_index=True, help_text='请求内容的哈希值', max_length=64, verbose_name='请求哈希')),
                ('request_data', models.JSONField(verbose_name='请求数据')),
                ('response_data', models.JSONField(verbose_name='响应数据')),
                ('token_usage', models.JSONField(default=dict, verbose_name='Token使用情况')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中次数')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': 'LLM请求缓存',
                'verbose_name_plural': 'LLM请求缓存',
                'db_table': 'llm_request_cache',
                'ordering': ['-last_accessed_at'],
                'indexes': [models.Index(fields=['model_name', 'request_hash'], name='llm_request_model_n_c03799_idx'), models.Index(fields=['expires_at'], name='llm_request_expires_f7ff73_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='日志ID')),
                ('request_id', models.CharField(default=uuid.uuid4, help_text='用于追踪和去重', max_length=100, unique=True, verbose_name='请求ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='会话ID')),
                ('call_type', models.CharField(choices=[('chat', '对话'), ('completion', '补全'), ('embedding', '嵌入'), ('structured', '结构化输出'), ('function', '函数调用'), ('tool', '工具调用')], default='chat', max_length=20, verbose_name='调用类型')),
                ('model_name', models.CharField(db_index=True, help_text='对应 router.LLMModel.name', max_length=128, verbose_name='模型名称')),
                ('model_id', models.CharField(blank=True, help_text='对应 router.LLMModel.model_id', max_length=128, verbose_name='模型标识符')),
                ('vendor_name', models.CharField(blank=True, help_text='对应 router.VendorEndpoint.vendor_name', max_length=128, verbose_name='供应商名称')),
                ('vendor_id', models.CharField(blank=True, help_text='对应 router.VendorEndpoint.vendor_id', max_length=64, verbose_name='供应商标识符')),
                ('endpoint', models.URLField(help_text='实际调用的API端点', max_length=500, verbose_name='调用端点')),
                ('request_messages', models.JSONField(default=list, help_text='发送给LLM的消息列表', verbose_name='请求消息')),
                ('request_params', models.JSONField(default=dict, help_text='temperature、max_tokens等参数', verbose_name='请求参数')),
                ('request_headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='请求时间')),
                ('response_content', models.TextField(blank=True, help_text='LLM返回的内容', verbose_name='响应内容')),
                ('response_raw', models.JSONField(blank=True, default=dict, help_text='完整的原始响应数据', verbose_name='原始响应')),
                ('response_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='错误代码')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('is_stream', models.BooleanField(default=False, verbose_name='是否流式')),
                ('prompt_tokens', models.IntegerField(blank=True, null=True, verbose_name='输入Token数')),
                ('completion_tokens', models.IntegerField(blank=True, null=True, verbose_name='输出Token数')),
                ('total_tokens', models.IntegerField(blank=True, null=True, verbose_name='总Token数')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, help_text='基于模型定价的预估成本', max_digits=10, null=True, verbose_name='预估成本(USD)')),
                ('source_app', models.CharField(blank=True, help_text='调用来源，如chat、agentic、knowledge等', max_length=50, verbose_name='来源应用')),
                ('source_function', models.CharField(blank=True, help_text='具体的调用函数或模块', max_length=100, verbose_name='来源函数')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外的自定义数据', verbose_name='元数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'LLM调用日志',
                'verbose_name_plural': 'LLM调用日志',
                'db_table': 'llm_call_log',
                'ordering': ['-request_timestamp'],
                'indexes': [models.Index(fields=['user', '-request_timestamp'], name='llm_call_lo_user_id_dcdfda_idx'), models.Index(fields=['model_name', '-request_timestamp'], name='llm_call_lo_model_n_bf6ab0_idx'), models.Index(fields=['session_id'], name='llm_call_lo_session_209be8_idx'), models.Index(fields=['status'], name='llm_call_lo_status_fd9a37_idx'), models.Index(fields=['source_app'], name='llm_call_lo_source__e2b8eb_idx'), models.Index(fields=['vendor_name'], name='llm_call_lo_vendor__15a001_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='对应 router.LLMModel.name', max_length=128, verbose_name='模型名称')),
                ('vendor_name', models.CharField(blank=True, max_length=128, verbose_name='供应商名称')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('hour', models.IntegerField(blank=True, help_text='0-23，用于小时级统计', null=True, verbose_name='小时')),
                ('period', models.CharField(choices=[('hourly', '每小时'), ('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=10, verbose_name='统计周期')),
                ('call_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('total_prompt_tokens', models.BigIntegerField(default=0, verbose_name='总输入Token')),
                ('total_completion_tokens', models.BigIntegerField(default=0, verbose_name='总输出Token')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='总Token数')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='总成本(USD)')),
                ('avg_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='平均耗时(毫秒)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_stats', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token使用统计',
                'verbose_name_plural': 'Token使用统计',
                'db_table': 'llm_token_usage',
                'ordering': ['-date', '-hour', 'user', 'model_name'],
                'indexes': [models.Index(fields=['user', '-date'], name='llm_token_u_user_id_38f030_idx'), models.Index(fields=['model_name', '-date'], name='llm_token_u_model_n_84cd31_idx'), models.Index(fields=['vendor_name', '-date'], name='llm_token_u_vendor__bd83ce_idx'), models.Index(fields=['date', 'period'], name='llm_token_u_date_82a3ba_idx')],
                'unique_together': {('user', 'model_name', 'date', 'hour', 'period')},
            },
        ),
    ]
