# Generated by Django 5.1.5 on 2025-09-11 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(default=0, help_text='步骤顺序号')),
                ('log_type', models.CharField(choices=[('planner', '规划器'), ('tool_call', '工具调用'), ('tool_result', '工具结果'), ('reflection', '反思'), ('final_answer', '最终答案'), ('todo_update', 'TODO更新')], help_text='日志类型', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='步骤详细信息，JSON格式')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '执行步骤',
                'verbose_name_plural': '执行步骤',
                'ordering': ['task', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='任务的唯一ID', unique=True)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '运行中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='PENDING', help_text='任务状态', max_length=50)),
                ('session_id', models.UUIDField(blank=True, db_index=True, help_text='会话ID（UUID），用于标识同一会话中的任务', null=True)),
                ('session_task_history', models.JSONField(blank=True, default=list, help_text='同一会话中历史任务的task_id集合')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='任务的输入数据，JSON格式')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='任务的输出数据，JSON格式')),
                ('state_snapshot', models.JSONField(blank=True, help_text="The serialized snapshot of the agent's RuntimeState.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='任务创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='任务最后更新时间')),
            ],
            options={
                'verbose_name': 'Agent 任务',
                'verbose_name_plural': 'Agent 任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_key', models.CharField(blank=True, help_text='条件路由的键。如果为空，则为无条件边。否则，只有当源节点返回此键时，该边才被激活。', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '边',
                'verbose_name_plural': '边',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='图的唯一名称', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='图的功能描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '图',
                'verbose_name_plural': '图',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='节点名称', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='对用户展示的节点别名', max_length=100, null=True)),
                ('node_type', models.CharField(choices=[('llm', '语言模型节点'), ('tool', '工具节点'), ('router', '路由/判断节点')], help_text='节点的类型', max_length=50)),
                ('python_callable', models.CharField(help_text="节点对应的Python可调用对象路径，例如 'myapp.tools.my_tool_func'", max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='初始化Python可调用对象时所需的参数')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
    ]
