# Generated by Django 5.1.5 on 2025-09-11 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='user',
            field=models.ForeignKey(blank=True, help_text='任务创建者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionsteps',
            name='task',
            field=models.ForeignKey(help_text='关联的Agent任务', on_delete=django.db.models.deletion.CASCADE, related_name='action_steps', to='agentic.agenttask'),
        ),
        migrations.AddField(
            model_name='edge',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='agentic.graph'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='graph',
            field=models.ForeignKey(blank=True, help_text='关联的Agentic Graph', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentic.graph'),
        ),
        migrations.AddField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agentic.graph'),
        ),
        migrations.AddField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(help_text='边的起始节点', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='agentic.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(help_text='边的目标节点', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='agentic.node'),
        ),
        migrations.AddIndex(
            model_name='actionsteps',
            index=models.Index(fields=['task', 'step_order'], name='agentic_act_task_id_e961b5_idx'),
        ),
        migrations.AddIndex(
            model_name='actionsteps',
            index=models.Index(fields=['log_type'], name='agentic_act_log_typ_184832_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('graph', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('source', 'condition_key')},
        ),
    ]
