# Generated by Django 5.1.5 on 2025-10-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='display_name',
            field=models.CharField(blank=True, help_text='对用户展示的节点别名', max_length=100, null=True, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agentic.graph', verbose_name='所属图'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(help_text='节点名称', max_length=255, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('llm', '语言模型节点'), ('tool', '工具节点'), ('router', '路由/判断节点')], help_text='节点的类型', max_length=50, verbose_name='节点类型'),
        ),
        migrations.AlterField(
            model_name='node',
            name='python_callable',
            field=models.CharField(help_text="节点对应的Python可调用对象路径，例如 'myapp.tools.my_tool_func'", max_length=255, verbose_name='Python可调用路径'),
        ),
    ]
